Feature/131
UofA-Blueprint/ICard pull request #27
Opened 2022-09-11 18:13 UTC by GurveerSohal

2022-09-16 02:59 UTC, dimassudjito requested changes

2022-09-18 20:40 UTC, dimassudjito commented
please solve merge conflict as well @GurveerSohal

2022-09-18 21:31 UTC, GurveerSohal commented on mobile/src/components/shared/SearchBar.jsx
> +        justifyContent: "space-evenly",
When I set it to 24, and the fontsize to 12, it is too small, the font is cut off. I think it is pixels, I tried using '24px' but it didn't work

2022-09-25 23:56 UTC, dimassudjito approved these changes

2022-09-25 23:56 UTC, merged