Feature/160
UofA-Blueprint/ICard pull request #28
Opened 2022-09-19 16:21 UTC by ArmaanKatyal

In this pull request:

- Added support for the JWT key for user session authentication.

2022-09-23 00:15 UTC, dimassudjito requested changes
Minor change needed: remove jwt middleware from vendors endpoint

2022-09-23 00:15 UTC, dimassudjito commented on backend/src/routes/Vendors.js
> +router.get('/', verifyApiKey, validateJwtToken, vendorController.getAll)
we don't need Jwt token to read vendors (since you don't need to login)

2022-09-23 00:34 UTC, dimassudjito commented
@ArmaanKatyal @TienDucHo 
Sorry, I forgot about the things that we discuss two weeks ago so correct me if I'm wrong:
1. The mobile app would log in users through google OAuth and get their email, name and picture. When they make query to /login to our backend, they'll be sending this data. They don't need to send idToken or any token from google.
2. Our backend will verify/create the user in the database and return data containing information about the user but also the JWT token which expires in 30 days.
3. The mobile app will use JTW token to make request to endpoint such as student (e.g., to update my icard page)

Question for @TienDucHo: do we get email, name, and picture directly when someone login or do we need to fetch it again from another google API? and if so, is there a performance issue with this method?

2022-09-23 02:03 UTC, ArmaanKatyal commented
> @ArmaanKatyal @TienDucHo Sorry, I forgot about the things that we discuss two weeks ago so correct me if I'm wrong:
> 
> 1. The mobile app would log in users through google OAuth and get their email, name and picture. When they make query to /login to our backend, they'll be sending this data. They don't need to send idToken or any token from google.
> 2. Our backend will verify/create the user in the database and return data containing information about the user but also the JWT token which expires in 30 days.
> 3. The mobile app will use JTW token to make request to endpoint such as student (e.g., to update my icard page)
> 
> Question for @TienDucHo: do we get email, name, and picture directly when someone login or do we need to fetch it again from another google API? and if so, is there a performance issue with this method?

we don't need to fetch all the details from google again as they are stored in our database when the user login for the first time. It will not create any performance issues. Yep, when the user logs in again he doesn't need the Id token as we have the jwt key there to verify.

2022-09-23 02:11 UTC, ArmaanKatyal commented
I will also add a route where duc can make requests to check if the jwt key is still valid or not. if not then the user has to log in again using the google id token. if jwt key is still valid then the user can access the data. Then we can merge this pull request.

Give me few more days. I will add this feature and test for the response time aswell.

2022-09-23 02:48 UTC, dimassudjito commented
> > @ArmaanKatyal @TienDucHo Sorry, I forgot about the things that we discuss two weeks ago so correct me if I'm wrong:
> > 
> > 1. The mobile app would log in users through google OAuth and get their email, name and picture. When they make query to /login to our backend, they'll be sending this data. They don't need to send idToken or any token from google.
> > 2. Our backend will verify/create the user in the database and return data containing information about the user but also the JWT token which expires in 30 days.
> > 3. The mobile app will use JTW token to make request to endpoint such as student (e.g., to update my icard page)
> > 
> > Question for @TienDucHo: do we get email, name, and picture directly when someone login or do we need to fetch it again from another google API? and if so, is there a performance issue with this method?
> 
> we don't need to fetch all the details from google again as they are stored in our database when the user login for the first time. It will not create any performance issues. Yep, when the user logs in again he doesn't need the Id token as we have the jwt key there to verify.

@ArmaanKatyal @TienDucHo 
Yes, but when they first login we would need to get the name and picture from google and I was wondering how this works (I now the first time duc made this, it takes like a minute to process and then suddenly it just got fast hahah)

2022-09-23 02:50 UTC, dimassudjito commented
> I will also add a route where duc can make requests to check if the jwt key is still valid or not. if not then the user has to log in again using the google id token. if jwt key is still valid then the user can access the data. Then we can merge this pull request.
> 
> Give me few more days. I will add this feature and test for the response time aswell.

@ArmaanKatyal 
Wouldn't it be better if the middleware that check jwt token also checks if the token has expired. If it has expired, it would send error message letting the app knows that the error is because token has expired

2022-09-23 02:51 UTC, dimassudjito requested changes

2022-09-23 02:51 UTC, dimassudjito commented on backend/src/services/verifyToken.js
> +    } catch (err) {
does jwt.verify() automatically check for expiry date of the token? we just need to make sure to throw descriptive error so we know when the token is expired and when it's just invalid

2022-09-23 03:28 UTC, dimassudjito commented
@ArmaanKatyal @TienDucHo 

Ok, I just talked with Duc on the standup meeting and I'm clear on how things work now. So, when the app first login, they will pass ID token that will be verified by the backend to get user information. So, the app doesn't have to pass user data such as name and URL picture. In another query like upload image and my icard data, the app will pass JWT which will authenticate their access to the backend.

Let me know if I'm accurate and I can create a documentation for this for the new dev.

2022-09-23 03:30 UTC, dimassudjito commented
Sorry for my confusion hahah, I missed the part where the login/ route still used the checkAuthenticated middleware

2022-10-11 19:43 UTC, dimassudjito requested changes

2022-10-11 19:43 UTC, dimassudjito commented on backend/src/routes/Vendors.js
> +router.get('/', verifyApiKey, validateJwtToken, vendorController.getAll)
@ArmaanKatyal can we fix this before we merge this PR

2022-10-13 16:56 UTC, dimassudjito approved these changes
Looks good! Please merge when you approve @MoyinF @yismailuofa

2022-10-19 03:59 UTC, merged