added Image attribute in vendor.js in backend
UofA-Blueprint/ICard pull request #35
Opened 2022-10-13 03:24 UTC by kunaal-gupta

I have added Image attribute in vendor.js in backend. Let me know if it doesn't work out

2022-10-13 05:10 UTC, MoyinF approved these changes
Looks good.

2022-10-13 05:20 UTC, MoyinF commented
Side note: are Youssef and I code owners here? I should have the option to merge after approving it

2022-10-13 16:40 UTC, dimassudjito commented
@MoyinF 
> Side note: are Youssef and I code owners here? I should have the option to merge after approving it

Yes, you and Yuossef are code owners for the entire repo, does it not allow you to merge it?

2022-10-13 16:52 UTC, dimassudjito requested changes
In general, we want to make the PR as specific as possible so don't include changes unrelated to the ticket. For example, your ticket only include backend work so there's no need to update the mobile folder unless we need to

2022-10-13 16:52 UTC, dimassudjito commented on mobile/package.json
> +    "react-native": "0.69.6",
I think updating the whole version could cause trouble for other people with older expo version. I know you're having problem with versioning and I'd suggest downgrading your expo version

2022-10-13 16:52 UTC, dimassudjito commented on backend/src/models/Vendor.js
> +        image: {                // Added this
delete unnecessary comment

2022-10-13 16:52 UTC, dimassudjito commented on mobile/package.json
> +    "react-native": "0.69.6",
my expo version: 6.0.1

2022-10-16 19:13 UTC, dimassudjito approved these changes

2022-10-19 04:00 UTC, merged